# Generated by Django 5.1.6 on 2025-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_image_url_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_interval',
            field=models.CharField(blank=True, choices=[('9-12', '9:00 - 12:00'), ('12-15', '12:00 - 15:00'), ('15-18', '15:00 - 18:00'), ('18-21', '18:00 - 21:00')], max_length=20, null=True, verbose_name='Временной интервал доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными при получении'), ('transfer', 'Переводом при получении')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_process', 'В процессе'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='in_process', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
