# Generated by Django 5.1.6 on 2025-05-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название товара (на момент заказа)'),
        ),
    ]
