server {
    server_name prime-forest.ru www.prime-forest.ru;

    # React фронтенд
    root /var/www/build;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Django API
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        client_max_body_size 50M;
    }

    # Django Admin
    location /admin/ {
        proxy_pass http://127.0.0.1:8000/admin/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    # Статические файлы React (обрабатываем первыми)
    location ~ ^/static/(js|css|media)/ {
        root /var/www/build;
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # Статические файлы Django (всё остальное в /static/)
    location /static/ {
        alias /var/www/primeforest.back/static/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    # Медиа файлы Django
    location /media/ {
        alias /var/www/primeforest.back/media/;
        expires 1d;
        add_header Cache-Control "public";
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/prime-forest.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/prime-forest.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.prime-forest.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = prime-forest.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name prime-forest.ru www.prime-forest.ru 89.104.70.180;

    listen 80;
    listen [::]:80;
    return 404; # managed by Certbot
}